---
title: "More Information"
---

```{r, include=FALSE}
# to use FA icons
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


## Contact

Email: mark.robinson (at) imls.uzh.ch  
Twitter <i class="fa fa-twitter"></i> [\@markrobinsonca](https://twitter.com/markrobinsonca)  
GitHub <i class="fa fa-github"></i> [robinsonlabuzh](https://github.com/robinsonlabuzh) and [markrobinsonuzh](https://github.com/markrobinsonuzh)

**Address:**

Institute of Molecular Life Sciences  
University of Zurich  
Winterthurerstrasse 190  
CH-8057 Zurich, Switzerland

Building / Room: Y11-J-16  
phone <i class="fa fa-phone"></i> +41 44 635 48 48  
fax <i class="fa fa-fax"></i> +41 44 635 68 68


## Links

[Institute of Molecular Life Sciences, University of Zurich](http://www.imls.uzh.ch/en.html)  
[Faculty of Science, University of Zurich](http://www.mnf.uzh.ch/en.html)  
[University of Zurich](http://www.uzh.ch/en.html)  
[Swiss Institute of Bioinformatics](https://www.sib.swiss/)



## Open positions

**Research Assistants**. From time to time, we have openings for dedicated numerically-inclined people (e.g., BSc or MSc in Statistics) who are interested in real-world genomics data analysis and gaining research experience before embarking on a PhD.Email me directly if you fit this description.  

**PhD Students**. Recruitment for PhD students is conducted through the [Life Science Zurich Graduate School](https://www.lifescience-graduateschool.uzh.ch/en.html), typically through the [Epidemiology and Biostatistics Structured PhD Program](http://www.epibiostat-phd.uzh.ch/en.html). For further information, please refer to the LSZGS website. Once selected, candidates can express an interest in our group; intake (and interviews) take place twice per year.  

**Postdoctoral fellows**. No positions are available at present. However, strong candidates are encouraged to email me directly and discuss an application for funding with UZH and other funding bodies.  


## Code of conduct

All members of the lab, along with visitors, are expected to agree with the following code of conduct. We will enforce this code as needed. We expect cooperation from all members to help ensuring a safe environment for everybody.

The lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof). We do not tolerate harassment of lab members in any form. Sexual language and imagery is generally not appropriate for any lab venue, including lab meetings, presentations, or discussions.

Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

Members asked to stop any harassing behavior are expected to comply immediately.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact Mark Robinson without hesitation.

For official concerns, please see the [University of Zurich House Regulations](http://www.uzh.ch/en/about/basics/houseregulations.html) website.

(This code of conduct is adapted from [Laurent Gatto, University of Cambridge](https://lgatto.github.io/cpu-coc/) and [Titus Brown, UC Davis](http://ivory.idyll.org/lab/coc.html).)


